//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISTAT.SingleSignON.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localisation
    {
        public string TableName { get; set; }
        public string Code { get; set; }
        public string Lang { get; set; }
        public string Description { get; set; }
        public int LocalisationID { get; set; }
    }
}
