//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISTAT.SingleSignON.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreference
    {
        public long UserPreferenceCode { get; set; }
        public string UserCode { get; set; }
        public string PreferenceCode { get; set; }
    
        public virtual Preference Preference { get; set; }
        public virtual User User { get; set; }
    }
}
