//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISTAT.SingleSignON.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserPreferences = new HashSet<UserPreference>();
        }
    
        public string UserCode { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Age { get; set; }
        public string Country { get; set; }
        public string Position { get; set; }
        public string Sex { get; set; }
        public string Study { get; set; }
        public string Agency { get; set; }
        public string Lang { get; set; }
        public string Role { get; set; }
    
        public virtual Age Age1 { get; set; }
        public virtual Agency Agency1 { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Language Language { get; set; }
        public virtual Position Position1 { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual Sex Sex1 { get; set; }
        public virtual Study Study1 { get; set; }
        public virtual ICollection<UserPreference> UserPreferences { get; set; }
    }
}
