//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estat.Nsi.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Estat.Nsi.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSICLIENT_NET.
        /// </summary>
        internal static string DefaultHeaderId {
            get {
                return ResourceManager.GetString("DefaultHeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string defaultLanguage {
            get {
                return ResourceManager.GetString("defaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter more criteria to reduce the size of the dataset..
        /// </summary>
        internal static string EnterMoreCriteria {
            get {
                return ResourceManager.GetString("EnterMoreCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIG ERROR:Cannot load the WSDL &apos;{0}&apos; for endpoint &apos;{1}&apos;.
        /// </summary>
        internal static string ExceptionCannotLoadWsdlFormat2 {
            get {
                return ResourceManager.GetString("ExceptionCannotLoadWsdlFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint is not set.
        /// </summary>
        internal static string ExceptionEndpointNotSet {
            get {
                return ResourceManager.GetString("ExceptionEndpointNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting GetCategorySchemes.
        /// </summary>
        internal static string ExceptionErrorGettingCategorySchemes {
            get {
                return ResourceManager.GetString("ExceptionErrorGettingCategorySchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while ExecuteQuery.
        /// </summary>
        internal static string ExceptionExecuteQuery {
            get {
                return ResourceManager.GetString("ExceptionExecuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting GetCodelist for {0}. Error : {1}.
        /// </summary>
        internal static string ExceptionGetCodelistFormat2 {
            get {
                return ResourceManager.GetString("ExceptionGetCodelistFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting GetDataflows.
        /// </summary>
        internal static string ExceptionGettingDataflow {
            get {
                return ResourceManager.GetString("ExceptionGettingDataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting GetStructure.
        /// </summary>
        internal static string ExceptionGettingStructure {
            get {
                return ResourceManager.GetString("ExceptionGettingStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero or more than one codelist returned by the server, for {0}.
        /// </summary>
        internal static string ExceptionInvalidNumberOfCodeListsFormat1 {
            get {
                return ResourceManager.GetString("ExceptionInvalidNumberOfCodeListsFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER RESPONSE getStructure ERROR: The number of keyFamilies is not 1.
        /// </summary>
        internal static string ExceptionKeyFamilyCountNot1 {
            get {
                return ResourceManager.GetString("ExceptionKeyFamilyCountNot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER RESPONSE getStructure ERROR: Missing referenced concept  scheme : {0}.
        /// </summary>
        internal static string ExceptionMissingConceptSchemeFormat1 {
            get {
                return ResourceManager.GetString("ExceptionMissingConceptSchemeFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER RESPONSE ERROR: Missing response.
        /// </summary>
        internal static string ExceptionMissingResponse {
            get {
                return ResourceManager.GetString("ExceptionMissingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER RESPONSE ERROR: Missing Structure from response.
        /// </summary>
        internal static string ExceptionMissingStructure {
            get {
                return ResourceManager.GetString("ExceptionMissingStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing the count codelist for {0}.
        /// </summary>
        internal static string ExceptionParsingCountCodelistFormat0 {
            get {
                return ResourceManager.GetString("ExceptionParsingCountCodelistFormat0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the NSIClient configuration .
        ///Reason :.
        /// </summary>
        internal static string ExceptionReadingConfiguration {
            get {
                return ResourceManager.GetString("ExceptionReadingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a SOAP FAULT: .
        /// </summary>
        internal static string ExceptionReceivedSoapFault {
            get {
                return ResourceManager.GetString("ExceptionReceivedSoapFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER RESPONSE ERROR: .
        /// </summary>
        internal static string ExceptionServerResponse {
            get {
                return ResourceManager.GetString("ExceptionServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER RESPONSE getStructure ERROR: The KeyFamily is not the same as the dataflow referenced keyfamily.
        /// </summary>
        internal static string ExceptionServerResponseInvalidKeyFamily {
            get {
                return ResourceManager.GetString("ExceptionServerResponseInvalidKeyFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero codes in codelist returned by the server, for {0}.
        /// </summary>
        internal static string ExceptionZeroCodesFormat1 {
            get {
                return ResourceManager.GetString("ExceptionZeroCodesFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER RESPONSE Failure.
        /// </summary>
        internal static string FailureFromServer {
            get {
                return ResourceManager.GetString("FailureFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataflow {0}, Codelist : {1}.
        /// </summary>
        internal static string InfoCountFormat2 {
            get {
                return ResourceManager.GetString("InfoCountFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new  NSI Client.
        /// </summary>
        internal static string InfoCreatingNsiClient {
            get {
                return ResourceManager.GetString("InfoCreatingNsiClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all category schemes.
        /// </summary>
        internal static string InfoGettingCategorySchemes {
            get {
                return ResourceManager.GetString("InfoGettingCategorySchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting codelist for {0}.
        /// </summary>
        internal static string InfoGettingCodelistFormat1 {
            get {
                return ResourceManager.GetString("InfoGettingCodelistFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all dataflows.
        /// </summary>
        internal static string InfoGettingDataFlows {
            get {
                return ResourceManager.GetString("InfoGettingDataFlows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting structure for {0}+{1}+{2}.
        /// </summary>
        internal static string InfoGettingStructureFormat3 {
            get {
                return ResourceManager.GetString("InfoGettingStructureFormat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve/Load WSDL....
        /// </summary>
        internal static string InfoGetWSDL {
            get {
                return ResourceManager.GetString("InfoGetWSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataflow {0}, Component : {1} , Codelist : {2}.
        /// </summary>
        internal static string InfoPartialCodelistFormat3 {
            get {
                return ResourceManager.GetString("InfoPartialCodelistFormat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soap RESPONSE :.
        /// </summary>
        internal static string InfoSoapResponse {
            get {
                return ResourceManager.GetString("InfoSoapResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |--Success.
        /// </summary>
        internal static string InfoSuccess {
            get {
                return ResourceManager.GetString("InfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        /// Expected location of web.config : {1}.
        /// </summary>
        internal static string InfoWebConfigLocation {
            get {
                return ResourceManager.GetString("InfoWebConfigLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `-- WSDL loaded successfully!.
        /// </summary>
        internal static string InfoWSDLSuccess {
            get {
                return ResourceManager.GetString("InfoWSDLSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has validation errors.
        /// </summary>
        internal static string LogMaintainableValidationErrors {
            get {
                return ResourceManager.GetString("LogMaintainableValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nsi WebService accepts less max_observations than NSI Client: {0}.
        /// </summary>
        internal static string MaxObservations {
            get {
                return ResourceManager.GetString("MaxObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Text: {0}, Code: {1}, Severity: {2}.
        /// </summary>
        internal static string SdmxFooterMessage {
            get {
                return ResourceManager.GetString("SdmxFooterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-ddTHH:mm:ss.
        /// </summary>
        internal static string SdmxHeaderPreparedDateTimeFormat {
            get {
                return ResourceManager.GetString("SdmxHeaderPreparedDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `-- {0}: {1}.
        /// </summary>
        internal static string StatusMessageFormat2 {
            get {
                return ResourceManager.GetString("StatusMessageFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER RESPONSE has warnings:.
        /// </summary>
        internal static string WarningFromServer {
            get {
                return ResourceManager.GetString("WarningFromServer", resourceCulture);
            }
        }
    }
}
